[package]
name = "lib_threadpools"
version = "0.1.2"
authors = ["R V Vivek <rvvaghu@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.3"
anyhow = "1.0"